### ISSUE TITLE
全体管理

### ISSUE THREAD

**Issue by mihye1128** [camp-team/team-mitsui#1]
## MTG
- [x] ブレストMTG (2020.10.03 20:00 start)
- [x] キックオフMTG (2020.10.10 10:00 start)
- [x] 初日経過報告MTG (2020.10.10 20:00 start)
- [x] 発表前MTG ＆ デバック (2020.10.11 14:00 start)

### 事前準備
- [x] 要件定義・設計 @mihye1128 
- [x] issueを立てる @mihye1128 
- [x] XDプロトタイプ作成(キックオフMTG用・作り込まない) @mihye1128 
- [x] Firebase作成 @mihye1128 
- [x] プロダクト名を考える @hide-a1  @yuuki-kouno @mihye1128  

### 環境構築
- [x] Angular #2 @mihye1128 
- [x] AngularMaterial #2 @mihye1128 
- [x] AngularFire #2 @mihye1128 
- [x] 自動Prettier #2 @mihye1128 
- [x] 自動deploy #3 @mihye1128 

### 画面作成
- [x] 共通画面：ヘッダー作成 #4 @mihye1128 
- [x] 共通画面：フッター作成 #5 @hide-a1 
- [x] イベント一覧画面：イベント一覧タブ（すべて / 管理イベント / 招待イベント） #6 @mihye1128
- [x] イベント一覧画面：イベント作成Dialog（イベント一覧画面で開く） #7  @mihye1128
- [x] イベント詳細画面：イベント詳細＋回答ボタン #8  @hide-a1  
- [x] イベント詳細画面：イベント回答者一覧タブ（参加 / 不参加 / 検討中） #9  @hide-a1 
- [x]  LP画面：ヒーロー #10 @hide-a1 @mihye1128 
- [x]  LP画面：機能紹介 #11 @hide-a1 @mihye1128 
- [x]  LP画面：活用例 #12 @hide-a1 @mihye1128 

### 機能実装
- [x] 機能実装：ログイン・ログアウト #13 @mihye1128 
- [x] 機能実装：イベント作成 #14 @mihye1128 
- [ ] 機能実装：イベント 回答 #15（参加 / 検討中 / 不参加） @hide-a1 
- [ ] 機能実装：イベント一覧出力 #30 @mihye1128
- [ ] 機能実装：ユーザー一覧出力 #31  @hide-a1 

### 機能実装・Functions
- [ ] 機能実装：イベント回答メール送信 #16 @yuuki-kouno

### 画面作成（余裕があればここまでする）
- [ ] イベント詳細画面：イベント編集Dialog（イベント詳細画面で開く）
- [ ] イベント詳細画面：イベント削除Dialog（イベント詳細画面で開く）
- [ ] アカウント設定画面：ユーザー情報編集・退会

### 機能実装・クライアント（余裕があればここまでする）
- [ ] 機能実装：イベント編集・削除
- [ ] 機能実装：ユーザー退会
- [ ] 機能実装：ユーザー情報編集

### 機能実装・Functions（余裕があればここまでする）
- [ ] 機能実装：イベントリマインダーメール送信

## 設計
![image](https://user-images.githubusercontent.com/46749854/95430362-a5fcae00-0986-11eb-9381-d016d3cfba88.png)

## プロトタイプ
https://xd.adobe.com/view/1c20a632-d697-4ccd-aa9f-4edc58bfea92-4973/
